### Sheet 1

In [1]:
import numpy as np
import pandas as pd

In [8]:
data = pd.ExcelFile('Techno-Economic-Comparison.xlsx')
print(data.sheet_names)

['assumptions', 'values', 'References', 'Elektrolyser', 'Water', 'Conversion', 'Liquefaction', 'Storage 1', 'Shipping', 'Storage 2', 'Reconversion', 'Utilization', 'Combined', 'Plots', 'TransportStorage', 'Sensitiv']

In [9]:
xl = pd.ExcelFile('Techno-Economic-Comparison.xlsx')

# Load a sheet into a DataFrame by its name
df1 = xl.parse('assumptions')
df1

,Unnamed: 0,Unit,Best Value,mean,Worst Value,Ref Value 0,Ref Value 1,Ref Value 2,Ref Value 3,Ref Value 4,...,Ref. 1,Ref. 2,Ref. 3,Ref. 4,Ref. 5,Ref. 6,Ref. 7,Ref. 8,Ref. 9,Ref. 10
0,Port costs LNG,[USD/day],100000.000000,100000.000000,100000.000000,NaN,100000,NaN,NaN,NaN,...,[13],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Suez Canal costs,[USD/LNG ship],300000.000000,400000.000000,500000.000000,NaN,300000,500000,NaN,NaN,...,[13] 160000m3,[13] 160000m3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,clean electricity cost,[USD/kWh],0.010000,0.040000,0.070000,0.01,0.07,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,electricity cost end country,[USD/kWh],0.070000,0.086454,0.104255,NaN,0.07,0.104255,0.085106,NaN,...,[64],[65] 2030,[65] 2040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,conversion Eur/USD,[EUR/USD],0.940000,0.940000,0.940000,0.94,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,(water price) not used,[USD/m^3],1.050000,1.825000,2.600000,NaN,2.6,1.05,NaN,NaN,...,[14] 2015,[14] 2050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Elektrolyzer hours per year,[h/year],5500.000000,4200.000000,2900.000000,NaN,5500,NaN,NaN,NaN,...,[16],[16],[16],NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Conversion hours per year,[h/year],8760.000000,8760.000000,8760.000000,NaN,8760,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Load hours per year,[h/year],5000.000000,3500.000000,2000.000000,5000.00,[5000],NaN,2000,[800],...,NaN,[44] (solid) biomass,[44] (solid) biomass,[96],[96],NaN,NaN,NaN,NaN,NaN
9,Stack Lifetime,[h],100000.000000,78000.000000,50000.000000,NaN,95000,100000,50000,80000,...,[1],[16],[2] (PEM 2020),[2] (PEM 2020),[2] (PEM 2020),NaN,NaN,NaN,NaN,NaN
10,Availability,-,1.000000,0.975000,1.000000,1.00,0.95,NaN,NaN,NaN,...,[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,WACC / discount rate,[%],0.080000,0.080000,0.080000,NaN,0.08,NaN,NaN,NaN,...,[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Storage Time 1,[days],30.000000,30.000000,30.000000,30.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Storage Time 2,[days],60.000000,60.000000,60.000000,60.00,[10],NaN,NaN,NaN,...,[42],[42],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Lifetime NH3 Sythese,[years],25.000000,25.000000,25.000000,NaN,25,NaN,NaN,NaN,...,[20],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Lifetime,[years],25.000000,25.000000,25.000000,25.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,iron ship operational day per year,[days/year],350.000000,350.000000,350.000000,NaN,350,NaN,NaN,NaN,...,[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Toluene lost per cycle,[%],0.100000,0.100000,0.100000,NaN,0.1,NaN,NaN,NaN,...,[9],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,hydrogenation efficiency,[%],97.000000,93.750000,90.000000,NaN,97,93,95,90,...,[9],[9],[9],[9],NaN,NaN,NaN,NaN,NaN,NaN
20,LOHC store in same tank,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,...,[52] page 60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,ship size,[m^3],NaN,NaN,NaN,NaN,160000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,CO2 price,NaN,0.265957,0.148936,0.031915,NaN,0.265957,0.031915,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Utilization H2: factor of CC CH4 CCGT PP,[-],1.050000,1.162500,1.250000,NaN,1.15,1.25,1.05,1.2,...,[43],[43],[95],[95],NaN,NaN,NaN,NaN,NaN,NaN
26,Utilization NH3: factor of CC CH4 CCGT PP (lik...,[-],1.050000,1.162500,1.250000,NaN,1.15,1.25,1.05,1.2,...,[43] same H2,[43] same H2,[95] same H2,[95] same H2,NaN,NaN,NaN,NaN,NaN,NaN
27,Utilization Iron: factor of CC Coal power plant,[-],0.100000,0.125000,0.150000,NaN,0.1,0.15,NaN,NaN,...,[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,efficiency CCGT CH4,[-],0.640000,0.606750,0.550000,NaN,0.64,0.6,0.55,0.637,...,[96],[43],[99],[99],[99] future,[100] future,NaN,NaN,NaN,NaN
29,efficiency CCGT H2,[-],0.620000,0.586750,0.530000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,efficiency iron power plant (coal),[-],0.500000,0.475000,0.450000,NaN,0.5,0.45,NaN,NaN,...,[1],[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,efficiency Ammonia only GT,[-],NaN,0.362000,NaN,NaN,0.362,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,OPEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Utilization: OPEX fix of CH4 CCGT Power Plant,[USD/kWel/year],21.276596,21.276596,21.276596,NaN,21.276596,"[=0,005*values!G73]","[=0,016*values!H73]",NaN,...,[44],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Utilization: OPEX fix of CH4 CCGT Power Plant,[USD/kWh],0.003191,0.003191,0.003191,NaN,0.003191,NaN,NaN,NaN,...,[44],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,OPEX factor,[% of CC],4.000000,4.000000,4.000000,NaN,4,NaN,NaN,NaN,...,[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,OPEX factor PEM Elektrolyzer,[% of CC],2.000000,3.333333,5.000000,NaN,2,NaN,3,5,...,[17],[17],[27],[102],NaN,NaN,NaN,NaN,NaN,NaN
38,OPEX factor NH3 Storage,[% of CC],2.000000,2.500000,3.000000,NaN,2.5,3,2,NaN,...,[9],[27],[17],NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,OPEX factor NH3 Synthesis,[% of CC],2.000000,2.833333,4.000000,NaN,2.5,4,2,NaN,...,[17],[17],[27],NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,OPEX H2 Liquefaction,[% of CC],2.500000,3.900000,5.000000,NaN,4,2.5,4,4,...,[16],[17],[9],[9],[27],NaN,NaN,NaN,NaN,NaN
41,H2 Storage Opex,[% of CC],2.000000,2.666667,4.000000,NaN,2,2,4,NaN,...,[36],[37],[31],NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,OPEX factor Regasification,[% of CC],2.500000,3.125000,4.000000,NaN,2.5,3,3,4,...,[17],[17],[9],[9],NaN,NaN,NaN,NaN,NaN,NaN
43,OPEX Cracking NH3,[% of CC],2.500000,3.125000,4.000000,NaN,3,4,2.5,3,...,[9],[9],[17],[17],NaN,NaN,NaN,NaN,NaN,NaN
44,OPEX Water,[% of CC],4.000000,4.150000,4.300000,NaN,4,4.3,NaN,NaN,...,[22],[27],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,OPEX storage LOHC,[% of CC],0.500000,2.040000,4.000000,NaN,4,3,0.7,0.5,...,[16],[17],[17],[17],[17],NaN,NaN,NaN,NaN,NaN
46,OPEX Hydrogenation (TOL),[% of CC],2.500000,3.375000,4.000000,NaN,2.5,4,3,4,...,[17],[17],[9],[9],NaN,NaN,NaN,NaN,NaN,NaN
47,OPEX Dehydrogenation (TOL),[% of CC],2.500000,3.875000,6.000000,NaN,2.5,4,3,6,...,[17],[17],[9],[9],NaN,NaN,NaN,NaN,NaN,NaN
48,OPEX Methanation,[% of CC],2.000000,3.460000,5.000000,NaN,4,3,3.3,2,...,[17],[17],[17],[27],[102],NaN,NaN,NaN,NaN,NaN
49,OPEX DAC,[% of CC],1.500000,3.500000,4.000000,NaN,4,4,4,1.5,...,[17],[60],[27],[86],[86],NaN,NaN,NaN,NaN,NaN
50,CH4 Opex Storage,[% of CC],2.000000,3.000000,4.000000,NaN,4,2,NaN,NaN,...,[31],[27],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,CH4 Opex liquefication,[% of CC],1.900000,2.700000,5.000000,NaN,1.9,2.1,2.5,2,...,[17],[17],[17],[27],NaN,NaN,NaN,NaN,NaN,NaN
52,OPEX methane cracking,[% of CC],4.000000,4.000000,4.000000,NaN,4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,OPEX iron storage,[% of CC],1.000000,1.000000,1.000000,NaN,1,NaN,NaN,NaN,...,[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,OPEX iron ship,[% of CC],4.000000,4.000000,4.000000,NaN,4,NaN,NaN,NaN,...,[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,OPEX DRI + EAF,[USD/t],45.000000,57.910000,70.820000,NaN,70.82,45,NaN,NaN,...,[67],[68],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df1.columns

Index(['Unnamed: 0', 'Unit', 'Best Value', 'mean', 'Worst Value',
       'Ref Value 0', 'Ref Value 1', 'Ref Value 2', 'Ref Value 3',
       'Ref Value 4', 'Ref Value 5', 'Ref Value 6', 'Ref Value 7',
       'Ref Value 8', 'Ref Value 9', 'Ref Value 10', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Ref. 1',
       'Ref. 2', 'Ref. 3', 'Ref. 4', 'Ref. 5', 'Ref. 6', 'Ref. 7', 'Ref. 8',
       'Ref. 9', 'Ref. 10'],
      dtype='object')

In [12]:
df1.describe()

,Best Value,mean,Worst Value,Ref Value 0,Ref Value 7,Ref Value 8,Ref Value 9,Ref Value 10,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Ref. 7,Ref. 8,Ref. 9,Ref. 10
count,48.000000,49.000000,48.000000,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,10832.628245,12146.779572,13842.073041,730.992857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,47152.881233,59329.781064,73425.653010,1882.581250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.003191,0.003191,0.003191,0.010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.985000,0.975000,1.000000,0.970000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.000000,3.125000,4.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,25.000000,25.000000,25.000000,45.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,300000.000000,400000.000000,500000.000000,5000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 31 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    52 non-null     object
 1   Unit          49 non-null     object
 2   Best Value    48 non-null     float64
 3   mean          49 non-null     float64
 4   Worst Value   48 non-null     float64
 5   Ref Value 0   7 non-null      float64
 6   Ref Value 1   47 non-null     object
 7   Ref Value 2   27 non-null     object
 8   Ref Value 3   21 non-null     object
 9   Ref Value 4   16 non-null     object
 10  Ref Value 5   9 non-null      object
 11  Ref Value 6   1 non-null      object
 12  Ref Value 7   0 non-null      float64
 13  Ref Value 8   0 non-null      float64
 14  Ref Value 9   0 non-null      float64
 15  Ref Value 10  0 non-null      float64
 16  Unnamed: 16   0 non-null      float64
 17  Unnamed: 17   0 non-null      float64
 18  Unnamed: 18   0 non-null      float64
 19  Unnamed: 19   0 non-null      float64
 20  Unnamed: 20   0 non-null      float64
 21  Ref. 1        40 non-null     object
 22  Ref. 2        28 non-null     object
 23  Ref. 3        21 non-null     object
 24  Ref. 4        16 non-null     object
 25  Ref. 5        7 non-null      object
 26  Ref. 6        1 non-null      object
 27  Ref. 7        0 non-null      float64
 28  Ref. 8        0 non-null      float64
 29  Ref. 9        0 non-null      float64
 30  Ref. 10       0 non-null      float64
dtypes: float64(17), object(14)
memory usage: 13.7+ KB

In [16]:
df1.isnull().sum()

Unnamed: 0       4
Unit             7
Best Value       8
mean             7
Worst Value      8
Ref Value 0     49
Ref Value 1      9
Ref Value 2     29
Ref Value 3     35
Ref Value 4     40
Ref Value 5     47
Ref Value 6     55
Ref Value 7     56
Ref Value 8     56
Ref Value 9     56
Ref Value 10    56
Unnamed: 16     56
Unnamed: 17     56
Unnamed: 18     56
Unnamed: 19     56
Unnamed: 20     56
Ref. 1          16
Ref. 2          28
Ref. 3          35
Ref. 4          40
Ref. 5          49
Ref. 6          55
Ref. 7          56
Ref. 8          56
Ref. 9          56
Ref. 10         56
dtype: int64

In [17]:
len(df1)

56

In [19]:
temp = df1['Unnamed: 0']

In [20]:
temp.unique

<bound method Series.unique of 0                                        Port costs LNG
1                                      Suez Canal costs
2                                clean electricity cost
3                          electricity cost end country
4                                    conversion Eur/USD
5                                (water price) not used
6                           Elektrolyzer hours per year
7                             Conversion hours per year
8                                   Load hours per year
9                                        Stack Lifetime
10                                         Availability
11                                 WACC / discount rate
12                                                  NaN
13                                       Storage Time 1
14                                      Storage Time 2
15                                Lifetime NH3 Sythese
16                                            Lifetime
17                   iron ship operational day per year
18                               Toluene lost per cycle
19                             hydrogenation efficiency
20                              LOHC store in same tank
21                                            ship size
22                                                  NaN
23                                            CO2 price
24                                                  NaN
25             Utilization H2: factor of CC CH4 CCGT PP
26    Utilization NH3: factor of CC CH4 CCGT PP (lik...
27      Utilization Iron: factor of CC Coal power plant
28                                  efficiency CCGT CH4
29                                   efficiency CCGT H2
30                   efficiency iron power plant (coal)
31                          efficiency Ammonia only GT
32                                                  NaN
33                                                 OPEX
34        Utilization: OPEX fix of CH4 CCGT Power Plant
35        Utilization: OPEX fix of CH4 CCGT Power Plant
36                                          OPEX factor
37                         OPEX factor PEM Elektrolyzer
38                              OPEX factor NH3 Storage
39                            OPEX factor NH3 Synthesis
40                                 OPEX H2 Liquefaction
41                                      H2 Storage Opex
42                           OPEX factor Regasification
43                                    OPEX Cracking NH3
44                                           OPEX Water
45                                    OPEX storage LOHC
46                             OPEX Hydrogenation (TOL)
47                           OPEX Dehydrogenation (TOL)
48                                     OPEX Methanation
49                                             OPEX DAC
50                                     CH4 Opex Storage
51                               CH4 Opex liquefication
52                                OPEX methane cracking
53                                    OPEX iron storage
54                                       OPEX iron ship
55                                       OPEX DRI + EAF
Name: Unnamed: 0, dtype: object>